export const municipalities = [
  {
    id: 1,
    name: 'みらい市',
    prefecture: '東京都',
    population: 15.2,
    planName: '第6次みらい市総合計画（2024〜2033年度）',
    direction: '「誰もが住みたい、住み続けたいまち」を目指し、デジタル技術を活用した行政サービスの効率化と、子育て世代に選ばれる地域づくりを推進する。',
    issues: [
      {
        id: 101,
        title: '行政手続きのオンライン化推進',
        description: '窓口手続きの85%がいまだ対面・紙ベース。住民の利便性向上と職員の業務効率化のため、主要手続きのオンライン化率を現状の15%から70%へ引き上げる。',
        budgetSection: { code: 'soumu', name: '総務費' },
        category: { id: 'dx', name: 'DX推進' },
        priority: 'high',
        kpiLabel: 'オンライン手続き率',
        kpiCurrent: '15%',
        kpiTarget: '70%',
      },
      {
        id: 102,
        title: '子育て支援施設の拡充',
        description: '待機児童数が県内ワースト3位。保育施設の新設と放課後児童クラブの拡充が急務。特に駅周辺の0〜2歳児受入枠の不足が深刻。',
        budgetSection: { code: 'minsei', name: '民生費' },
        category: { id: 'kosodate', name: '子育て支援' },
        priority: 'high',
        kpiLabel: '待機児童数',
        kpiCurrent: '120人',
        kpiTarget: '0人',
      },
      {
        id: 103,
        title: '防災情報伝達システムの刷新',
        description: '防災無線の老朽化が進み、難聴地域が市域の30%に達する。スマートフォンアプリやSNSと連携した多層的な情報伝達体制を構築する。',
        budgetSection: { code: 'shoubo', name: '消防費' },
        category: { id: 'infra', name: 'インフラ整備' },
        priority: 'medium',
        kpiLabel: '防災情報到達率',
        kpiCurrent: '70%',
        kpiTarget: '95%',
      },
      {
        id: 104,
        title: '観光コンテンツのデジタル化',
        description: '年間観光客数がコロナ前比で60%にとどまる。歴史的資源をデジタルコンテンツ化し、体験型観光を推進して観光消費額の回復を図る。',
        budgetSection: { code: 'shoukou', name: '商工費' },
        category: { id: 'kanko', name: '観光振興' },
        priority: 'medium',
        kpiLabel: '年間観光客数',
        kpiCurrent: '18万人',
        kpiTarget: '30万人',
      },
    ],
  },
  {
    id: 2,
    name: 'さくら町',
    prefecture: '埼玉県',
    population: 3.8,
    planName: 'さくら町まち・ひと・しごと創生総合戦略（2023〜2027年度）',
    direction: '豊かな自然環境を活かしながら、移住・定住促進とスマート農業の導入により、持続可能な農村地域のモデルケースを目指す。',
    issues: [
      {
        id: 201,
        title: '移住・定住促進策の強化',
        description: '20代〜30代の転出超過が年間200人規模で続いている。リモートワーク環境の整備、お試し居住制度、移住支援金制度の拡充で転入を増やす。',
        budgetSection: { code: 'soumu', name: '総務費' },
        category: { id: 'chiiki', name: '地域活性化' },
        priority: 'high',
        kpiLabel: '年間移住者数',
        kpiCurrent: '45世帯',
        kpiTarget: '120世帯',
      },
      {
        id: 202,
        title: 'スマート農業の導入推進',
        description: '農業従事者の平均年齢が68歳、後継者不在率が60%。IoTセンサーやドローンを活用した省力化により、少人数でも維持可能な農業体制を構築する。',
        budgetSection: { code: 'nourin', name: '農林水産業費' },
        category: { id: 'dx', name: 'DX推進' },
        priority: 'high',
        kpiLabel: 'スマート農業導入農家率',
        kpiCurrent: '5%',
        kpiTarget: '30%',
      },
      {
        id: 203,
        title: '空き家の利活用促進',
        description: '空き家率が18%に上昇。空き家バンクの活性化とリノベーション支援により、移住者向け住居や地域交流拠点として再活用を進める。',
        budgetSection: { code: 'doboku', name: '土木費' },
        category: { id: 'chiiki', name: '地域活性化' },
        priority: 'medium',
        kpiLabel: '空き家利活用件数',
        kpiCurrent: '12件/年',
        kpiTarget: '50件/年',
      },
    ],
  },
  {
    id: 3,
    name: 'はるか市',
    prefecture: '神奈川県',
    population: 28.5,
    planName: 'はるか市総合計画2025（2025〜2034年度）',
    direction: '県内有数のベッドタウンとして発展してきた強みを活かし、「職住近接のスマートシティ」への転換を図る。駅前再開発とMaaS導入が柱。',
    issues: [
      {
        id: 301,
        title: 'MaaS（次世代交通）の導入',
        description: '高齢ドライバーの免許返納率が低く、交通事故が増加傾向。オンデマンド交通とMaaSアプリの導入により、車に依存しない移動環境を実現する。',
        budgetSection: { code: 'doboku', name: '土木費' },
        category: { id: 'dx', name: 'DX推進' },
        priority: 'high',
        kpiLabel: '公共交通利用率',
        kpiCurrent: '22%',
        kpiTarget: '40%',
      },
      {
        id: 302,
        title: '脱炭素社会の実現',
        description: '2050年カーボンニュートラル宣言を掲げるも具体的施策が不足。公共施設の太陽光発電導入とEV充電インフラの整備を加速させる。',
        budgetSection: { code: 'eisei', name: '衛生費' },
        category: { id: 'kankyo', name: '環境・エネルギー' },
        priority: 'high',
        kpiLabel: 'CO2排出削減率（2013年比）',
        kpiCurrent: '18%減',
        kpiTarget: '46%減',
      },
      {
        id: 303,
        title: '学校教育のICT活用推進',
        description: 'GIGAスクール端末の活用率に学校間格差がある。教員向けICT研修の充実と、デジタル教材の共同調達により全校で均質な教育DXを進める。',
        budgetSection: { code: 'kyouiku', name: '教育費' },
        category: { id: 'dx', name: 'DX推進' },
        priority: 'medium',
        kpiLabel: 'ICT活用授業実施率',
        kpiCurrent: '35%',
        kpiTarget: '80%',
      },
    ],
  },
  {
    id: 4,
    name: 'あおば村',
    prefecture: '長野県',
    population: 0.8,
    planName: 'あおば村過疎地域持続的発展計画（2022〜2027年度）',
    direction: '人口800人の小規模自治体ならではの「顔の見える福祉」を強みに、デジタル技術で支え合いの仕組みを高度化する。',
    issues: [
      {
        id: 401,
        title: '高齢者見守りシステムの導入',
        description: '65歳以上比率が52%で独居高齢者が増加。IoTセンサーと地域の見守りネットワークを組み合わせた安否確認システムを導入する。',
        budgetSection: { code: 'minsei', name: '民生費' },
        category: { id: 'dx', name: 'DX推進' },
        priority: 'high',
        kpiLabel: '見守り対象カバー率',
        kpiCurrent: '30%',
        kpiTarget: '90%',
      },
      {
        id: 402,
        title: '遠隔医療体制の整備',
        description: '村内に診療所が1カ所のみで医師の高齢化が進む。オンライン診療と巡回診療車の組み合わせにより、住民が安心して暮らせる医療体制を維持する。',
        budgetSection: { code: 'eisei', name: '衛生費' },
        category: { id: 'infra', name: 'インフラ整備' },
        priority: 'high',
        kpiLabel: '遠隔診療利用率',
        kpiCurrent: '0%',
        kpiTarget: '40%',
      },
    ],
  },
  {
    id: 5,
    name: 'うみかぜ市',
    prefecture: '千葉県',
    population: 12.1,
    planName: 'うみかぜ市総合計画後期基本計画（2024〜2028年度）',
    direction: '海洋資源と港湾機能を活かした産業振興と、津波・高潮対策を両立する「海と共生するまちづくり」を推進する。',
    issues: [
      {
        id: 501,
        title: '沿岸部の防災インフラ強化',
        description: '南海トラフ地震を想定した津波避難タワーの整備が計画の40%で遅延。避難経路のデジタルサイネージ設置と住民避難訓練アプリの導入を進める。',
        budgetSection: { code: 'shoubo', name: '消防費' },
        category: { id: 'infra', name: 'インフラ整備' },
        priority: 'high',
        kpiLabel: '津波避難施設カバー率',
        kpiCurrent: '55%',
        kpiTarget: '100%',
      },
      {
        id: 502,
        title: 'ふるさと納税の戦略的強化',
        description: 'ふるさと納税受入額が県内中位にとどまる。海産物のブランド化とECサイト連携による返礼品の魅力向上で、自主財源の確保を図る。',
        budgetSection: { code: 'soumu', name: '総務費' },
        category: { id: 'chiiki', name: '地域活性化' },
        priority: 'medium',
        kpiLabel: 'ふるさと納税受入額',
        kpiCurrent: '2.8億円',
        kpiTarget: '8億円',
      },
    ],
  },
];

export const services = [
  {
    id: 1,
    companyName: '株式会社デジタルガバメント',
    title: '自治体DX統合プラットフォーム「GovTech Suite」',
    category: { id: 'dx', name: 'DX推進' },
    budgetSections: [
      { code: 'soumu', name: '総務費' },
    ],
    description: '住民向けオンライン申請、庁内ワークフロー、データ分析を一体化したクラウドサービス。導入自治体のオンライン手続き率を平均40%向上。',
    matchingIssueIds: [101, 301],
  },
  {
    id: 2,
    companyName: '子育てテック株式会社',
    title: '保育施設マッチングAI「ほいくナビ」',
    category: { id: 'kosodate', name: '子育て支援' },
    budgetSections: [
      { code: 'minsei', name: '民生費' },
    ],
    description: '待機児童の解消を支援するAIマッチングシステム。保護者の希望と施設の空き状況をリアルタイムで最適化。導入自治体で待機児童を平均60%削減。',
    matchingIssueIds: [102],
  },
  {
    id: 3,
    companyName: 'セーフティリンク株式会社',
    title: '多層防災情報プラットフォーム「BOSAI-Link」',
    category: { id: 'infra', name: 'インフラ整備' },
    budgetSections: [
      { code: 'shoubo', name: '消防費' },
    ],
    description: '防災無線、アプリ、SNS、デジタルサイネージを統合した災害情報配信システム。多言語対応、要配慮者への個別通知機能搭載。',
    matchingIssueIds: [103, 501],
  },
  {
    id: 4,
    companyName: '株式会社アグリDX',
    title: 'スマート農業パッケージ「FarmOS」',
    category: { id: 'dx', name: 'DX推進' },
    budgetSections: [
      { code: 'nourin', name: '農林水産業費' },
    ],
    description: 'IoTセンサー、ドローン、AI解析を一体化した農業支援システム。高齢農家でも簡単に使えるUIで、収量20%向上・労働時間30%削減を実現。',
    matchingIssueIds: [202],
  },
  {
    id: 5,
    companyName: '地域モビリティ株式会社',
    title: 'オンデマンド交通システム「MaaS Connect」',
    category: { id: 'dx', name: 'DX推進' },
    budgetSections: [
      { code: 'doboku', name: '土木費' },
    ],
    description: 'AIが需要を予測し最適ルートで運行するオンデマンド乗合交通。既存の公共交通とシームレスに連携するMaaSアプリ付き。',
    matchingIssueIds: [301],
  },
  {
    id: 6,
    companyName: '株式会社グリーンエナジー',
    title: '自治体向け再エネ導入コンサルティング',
    category: { id: 'kankyo', name: '環境・エネルギー' },
    budgetSections: [
      { code: 'eisei', name: '衛生費' },
    ],
    description: '公共施設への太陽光発電・蓄電池導入からEV充電インフラ整備まで、自治体のカーボンニュートラル達成を包括的に支援。',
    matchingIssueIds: [302],
  },
  {
    id: 7,
    companyName: 'みまもりテック株式会社',
    title: 'IoT高齢者見守りサービス「つながり」',
    category: { id: 'dx', name: 'DX推進' },
    budgetSections: [
      { code: 'minsei', name: '民生費' },
    ],
    description: '電力センサー、ドアセンサー、緊急ボタンを組み合わせた独居高齢者の見守りシステム。地域の民生委員・社協との連携機能付き。',
    matchingIssueIds: [401],
  },
  {
    id: 8,
    companyName: '観光DX株式会社',
    title: 'AR観光ガイド「たびナビ」',
    category: { id: 'kanko', name: '観光振興' },
    budgetSections: [
      { code: 'shoukou', name: '商工費' },
    ],
    description: 'スマートフォンのARカメラで歴史的建造物や景勝地の情報を重ね合わせ表示。多言語対応のデジタルスタンプラリー機能で回遊性を向上。',
    matchingIssueIds: [104],
  },
];

export const budgetSections = [
  { code: 'gikai',   name: '議会費',       color: '#64748b' },
  { code: 'soumu',   name: '総務費',       color: '#6366f1' },
  { code: 'minsei',  name: '民生費',       color: '#f43f5e' },
  { code: 'eisei',   name: '衛生費',       color: '#10b981' },
  { code: 'roudo',   name: '労働費',       color: '#f59e0b' },
  { code: 'nourin',  name: '農林水産業費', color: '#84cc16' },
  { code: 'shoukou', name: '商工費',       color: '#f97316' },
  { code: 'doboku',  name: '土木費',       color: '#78716c' },
  { code: 'shoubo',  name: '消防費',       color: '#ef4444' },
  { code: 'kyouiku', name: '教育費',       color: '#0ea5e9' },
  { code: 'saigai',  name: '災害復旧費',   color: '#a855f7' },
  { code: 'kousai',  name: '公債費',       color: '#9ca3af' },
];

export const categories = [
  { id: 'kanko',    name: '観光振興',         color: '#3b82f6' },
  { id: 'kosodate', name: '子育て支援',       color: '#ec4899' },
  { id: 'dx',       name: 'DX推進',           color: '#8b5cf6' },
  { id: 'infra',    name: 'インフラ整備',     color: '#eab308' },
  { id: 'chiiki',   name: '地域活性化',       color: '#22c55e' },
  { id: 'kankyo',   name: '環境・エネルギー', color: '#14b8a6' },
];
